import type {
  CallRecord,
  Characteristic,
  PeriodId,
  PeriodStats,
} from './types'

export const TABS = [
  { id: 'dashboard', label: 'Дашборд' },
  { id: 'calls', label: 'Звонки' },
  { id: 'chats', label: 'Чаты' },
  { id: 'views', label: 'Представления' },
  { id: 'characteristics', label: 'Характеристики' },
  { id: 'settings', label: 'Настройки' },
] as const

export const PERIODS: Array<{ id: PeriodId; label: string }> = [
  { id: 'this-week', label: 'Эта неделя' },
  { id: 'last-week', label: 'Прошлая неделя' },
  { id: '30d', label: '30 дней' },
  { id: 'this-month', label: 'Этот месяц' },
  { id: 'all', label: 'Всё время' },
  { id: 'custom', label: 'Свой период' },
]

const managersThisWeek = [
  { employee: 'Марина К.', conversations: 62, score: 84.5, script: 86.2, talkShare: 30.1, nextStep: 71.0 },
  { employee: 'Дмитрий С.', conversations: 54, score: 79.8, script: 81.4, talkShare: 41.7, nextStep: 64.4 },
  { employee: 'Ольга В.', conversations: 47, score: 76.1, script: 77.9, talkShare: 44.2, nextStep: 58.3 },
  { employee: 'Сергей П.', conversations: 38, score: 68.9, script: 66.5, talkShare: 47.6, nextStep: 41.2 },
  { employee: 'Без исполнителя', conversations: 13, score: 71.3, script: 70.1, talkShare: 40.2, nextStep: 35.0 },
]

function scaleManagers(
  rows: typeof managersThisWeek,
  factor: number,
): typeof managersThisWeek {
  return rows.map((row) => ({
    ...row,
    conversations: Math.max(1, Math.round(row.conversations * factor)),
    score: Number((row.score + (factor - 1) * 1.2).toFixed(1)),
    script: Number((row.script + (factor - 1) * 0.8).toFixed(1)),
    talkShare: Number((row.talkShare - (factor - 1) * 0.4).toFixed(1)),
    nextStep: Number((row.nextStep + (factor - 1) * 1.4).toFixed(1)),
  }))
}

const weeksBase = [
  { label: '24.08', calls: 42, script: 71, nextStep: 54 },
  { label: '31.08', calls: 48, script: 73, nextStep: 56 },
  { label: '07.09', calls: 53, script: 76, nextStep: 60 },
  { label: '14.09', calls: 58, script: 78, nextStep: 66 },
]

export const PERIOD_STATS: Record<Exclude<PeriodId, 'custom'>, PeriodStats> = {
  'this-week': {
    conversations: 214,
    score: 78.4,
    script: 74.2,
    talkShare: 45.8,
    managers: managersThisWeek,
    weeks: weeksBase,
  },
  'last-week': {
    conversations: 198,
    score: 76.1,
    script: 72.8,
    talkShare: 46.4,
    managers: scaleManagers(managersThisWeek, 0.92),
    weeks: weeksBase.slice(0, 3).concat([{ label: '07.09', calls: 53, script: 76, nextStep: 60 }]),
  },
  '30d': {
    conversations: 812,
    score: 77.6,
    script: 73.9,
    talkShare: 44.1,
    managers: scaleManagers(managersThisWeek, 3.7),
    weeks: weeksBase,
  },
  'this-month': {
    conversations: 486,
    score: 77.9,
    script: 74.0,
    talkShare: 44.9,
    managers: scaleManagers(managersThisWeek, 2.2),
    weeks: weeksBase.slice(2),
  },
  all: {
    conversations: 1940,
    score: 75.2,
    script: 71.4,
    talkShare: 46.8,
    managers: scaleManagers(managersThisWeek, 8.6),
    weeks: [
      { label: '03.08', calls: 38, script: 68, nextStep: 49 },
      ...weeksBase,
    ],
  },
}

export const SCORE_NORM = 70
export const SCRIPT_NORM = 70
export const TALK_SHARE_NORM = 43

function anonymizeCallClients(calls: CallRecord[]): CallRecord[] {
  const labels = new Map<string, string>()
  let n = 0
  return calls.map((call) => {
    const key = call.company !== '—' ? call.company : call.client
    let label = labels.get(key)
    if (!label) {
      n += 1
      label = `Клиент ${n}`
      labels.set(key, label)
    }
    return { ...call, client: label, company: label }
  })
}

const RAW_CALLS: CallRecord[] = [
  {
    id: 'c2',
    date: '2026-09-17T16:40:00',
    employee: 'Дмитрий С.',
    client: 'Крылова Е. А.',
    company: 'Крылова Е. А.',
    durationSec: 183,
    replies: 43,
    score: 12.0,
    type: 'Закрытие',
    status: 'analyzed',
    talkShare: 41.2,
    nextStep: true,
    scriptCompliance: 22,
    fileName: '83314077716526_out_79104699780_2026_09_17-13_40_07_6xk.mp3',
    summary: 'Сейл сразу перешёл к цене. Потребность не выявлена, ценность не донесена.',
  },
  {
    id: 'c3',
    date: '2026-09-17T16:34:00',
    employee: 'Ольга В.',
    client: 'АльфаСтрой',
    company: 'АльфаСтрой',
    durationSec: 521,
    replies: 72,
    score: 26.0,
    type: 'Онбординг',
    status: 'analyzed',
    talkShare: 39.7,
    nextStep: true,
    scriptCompliance: 41,
    fileName: '79021289558_in_79587093322_2026_09_17-13_34_29_d3zy.mp3',
    summary: 'Онбординг прошёл по чек-листу, но демо отложено без конкретной даты.',
  },
  {
    id: 'c4',
    date: '2026-09-17T16:12:00',
    employee: null,
    client: '79615708133',
    company: '—',
    durationSec: null,
    replies: null,
    score: null,
    type: null,
    status: 'queued',
    talkShare: null,
    nextStep: null,
    scriptCompliance: null,
    fileName: '8331400007156996_out_79615708133_2026_09_17-13_12_04_vera.mp3',
    summary: 'Запись в очереди на разбор.',
  },
  {
    id: 'c5',
    date: '2026-09-17T15:54:00',
    employee: 'Сергей П.',
    client: 'ТехноДом',
    company: 'ТехноДом',
    durationSec: 123,
    replies: 19,
    score: 15.0,
    type: 'Контрольный звонок',
    status: 'analyzed',
    talkShare: 49.8,
    nextStep: false,
    scriptCompliance: 20,
    fileName: '883140777409555_out_792347411_2026_09_17-12_54_17_k6xko.mp3',
    summary: 'Короткий контрольный звонок. Клиент занят, перезвон не согласован.',
  },
  {
    id: 'c6',
    date: '2026-09-17T14:50:00',
    employee: null,
    client: '79104699780',
    company: '—',
    durationSec: null,
    replies: null,
    score: null,
    type: null,
    status: 'error',
    talkShare: null,
    nextStep: null,
    scriptCompliance: null,
    fileName: '_833140777816526_out_79104699780_2026_09_17-13_40_07_6xk.mp3',
    summary: 'Не удалось распознать речь: повреждённый файл.',
  },
  {
    id: 'c7',
    date: '2026-09-17T14:50:00',
    employee: null,
    client: '79293841772',
    company: '—',
    durationSec: null,
    replies: null,
    score: null,
    type: null,
    status: 'error',
    talkShare: null,
    nextStep: null,
    scriptCompliance: null,
    fileName: '_833140777409555_out_79293841772_2026_09_17-11_33_41_ydg3.mp3',
    summary: 'Ошибка транскрибации: тишина длиннее 90 секунд.',
  },
  {
    id: 'c8',
    date: '2026-09-18T11:15:00',
    employee: 'Дмитрий С.',
    client: 'Крылова Е. А.',
    company: 'Крылова Е. А.',
    durationSec: 412,
    replies: 54,
    score: 74,
    type: 'Контрольный звонок',
    status: 'analyzed',
    talkShare: 41.2,
    nextStep: true,
    scriptCompliance: 81,
    fileName: 'dmitry_krylova_control.mp3',
    summary: 'Контроль после внедрения. Клиент подтвердил использование, назначен созвон с ЛПР.',
  },
  {
    id: 'c9',
    date: '2026-09-18T12:42:00',
    employee: 'Марина К.',
    client: 'Вектор Плюс',
    company: 'Вектор Плюс',
    durationSec: 638,
    replies: 81,
    score: 86,
    type: 'Онбординг',
    status: 'analyzed',
    talkShare: 38.4,
    nextStep: true,
    scriptCompliance: 88,
    fileName: 'marina_vector_onboarding.mp3',
    summary: 'Онбординг закрыт по чек-листу. Следующий шаг — пилот на 10 номерах в понедельник.',
  },
  {
    id: 'c10',
    date: '2026-09-18T10:03:00',
    employee: 'Ольга В.',
    client: 'АльфаСтрой',
    company: 'АльфаСтрой',
    durationSec: 490,
    replies: 61,
    score: 81,
    type: 'Закрытие',
    status: 'analyzed',
    talkShare: 39.7,
    nextStep: true,
    scriptCompliance: 79,
    fileName: 'olga_alfa_close.mp3',
    summary: 'Возражение по цене отработано через сравнение с текущим подрядчиком. КП отправлено.',
  },
  {
    id: 'c11',
    date: '2026-09-17T17:48:00',
    employee: 'Сергей П.',
    client: 'ТехноДом',
    company: 'ТехноДом',
    durationSec: 355,
    replies: 47,
    score: 63,
    type: 'Работа с возражениями',
    status: 'analyzed',
    talkShare: 49.8,
    nextStep: false,
    scriptCompliance: 58,
    fileName: 'sergey_techno_objection.mp3',
    summary: 'Клиент сравнил с более дешёвым решением. Сейл сразу предложил скидку, не уточнив критерии.',
  },
  {
    id: 'c12',
    date: '2026-09-17T16:20:00',
    employee: 'Марина К.',
    client: 'Северный ветер',
    company: 'Северный ветер',
    durationSec: 574,
    replies: 69,
    score: 88,
    type: 'Закрытие',
    status: 'analyzed',
    talkShare: 36.1,
    nextStep: true,
    scriptCompliance: 91,
    fileName: 'marina_sever_close.mp3',
    summary: 'Сделка сдвинута: счёт согласован, подпись — в пятницу у финансового директора.',
  },
  {
    id: 'c13',
    date: '2026-09-16T11:20:00',
    employee: 'Марина К.',
    client: 'Норд Логистик',
    company: 'Норд Логистик',
    durationSec: 447,
    replies: 58,
    score: 82,
    type: 'Первый контакт',
    status: 'analyzed',
    talkShare: 29.4,
    nextStep: true,
    scriptCompliance: 84,
    fileName: 'marina_nord_first.mp3',
    summary: 'Квалификация пройдена. Назначена встреча с РОПом клиента на четверг.',
  },
  {
    id: 'c14',
    date: '2026-09-15T15:05:00',
    employee: 'Дмитрий С.',
    client: 'ИнфоСервис',
    company: 'ИнфоСервис',
    durationSec: 301,
    replies: 40,
    score: 71,
    type: 'Первый контакт',
    status: 'analyzed',
    talkShare: 43.8,
    nextStep: true,
    scriptCompliance: 73,
    fileName: 'dmitry_infoservice_first.mp3',
    summary: 'Интерес есть, бюджет не подтверждён. Договорились прислать кейс и перезвонить.',
  },
  {
    id: 'c15',
    date: '2026-09-12T13:40:00',
    employee: 'Ольга В.',
    client: 'МеталлПром',
    company: 'МеталлПром',
    durationSec: 266,
    replies: 33,
    score: 69,
    type: 'Работа с возражениями',
    status: 'analyzed',
    talkShare: 46.2,
    nextStep: false,
    scriptCompliance: 64,
    fileName: 'olga_metall_obj.mp3',
    summary: 'Клиент «подумает». Конкретный следующий шаг не зафиксирован.',
  },
  {
    id: 'c16',
    date: '2026-09-10T09:55:00',
    employee: 'Сергей П.',
    client: 'Группа Эталон',
    company: 'Группа Эталон',
    durationSec: 198,
    replies: 28,
    score: 54,
    type: 'Контрольный звонок',
    status: 'analyzed',
    talkShare: 51.3,
    nextStep: false,
    scriptCompliance: 48,
    fileName: 'sergey_etalon_control.mp3',
    summary: 'Сейл говорил больше клиента. Вопрос про использование продукта не задан.',
  },
  {
    id: 'c17',
    date: '2026-09-03T14:10:00',
    employee: 'Марина К.',
    client: 'СибНефть Сервис',
    company: 'СибНефть Сервис',
    durationSec: 512,
    replies: 66,
    score: 90,
    type: 'Закрытие',
    status: 'analyzed',
    talkShare: 31.8,
    nextStep: true,
    scriptCompliance: 92,
    fileName: 'marina_sibneft_close.mp3',
    summary: 'Закрытие по скрипту. Договор у юристов, старт — 1 октября.',
  },
  {
    id: 'c18',
    date: '2026-08-27T16:22:00',
    employee: 'Дмитрий С.',
    client: 'Вектор Плюс',
    company: 'Вектор Плюс',
    durationSec: 389,
    replies: 49,
    score: 77,
    type: 'Онбординг',
    status: 'analyzed',
    talkShare: 40.5,
    nextStep: true,
    scriptCompliance: 80,
    fileName: 'dmitry_vector_onboard.mp3',
    summary: 'Первый онбординг. Доступы собраны, пилот согласован на следующую неделю.',
  },
  {
    id: 'c19',
    date: '2026-08-21T10:18:00',
    employee: 'Ольга В.',
    client: 'АртЛайн',
    company: 'АртЛайн',
    durationSec: 244,
    replies: 31,
    score: 73,
    type: 'Первый контакт',
    status: 'analyzed',
    talkShare: 42.0,
    nextStep: true,
    scriptCompliance: 75,
    fileName: 'olga_artline_first.mp3',
    summary: 'Тёплый вход с мероприятия. Назначена демонстрация на пятницу.',
  },
  {
    id: 'c20',
    date: '2026-09-18T09:12:00',
    employee: 'Марина К.',
    client: 'Байкал Трейд',
    company: 'Байкал Трейд',
    durationSec: 418,
    replies: 52,
    score: 85,
    type: 'Работа с возражениями',
    status: 'analyzed',
    talkShare: 33.2,
    nextStep: true,
    scriptCompliance: 87,
    fileName: 'marina_baikal_obj.mp3',
    summary: 'Возражение «уже есть подрядчик» закрыто кейсом. Запросили коммерческое к среде.',
  },
]

export const INITIAL_CALLS: CallRecord[] = anonymizeCallClients(RAW_CALLS)

export const INITIAL_CHARACTERISTICS: Characteristic[] = [
  {
    id: 'ch1',
    name: 'LLM: время до первого токена',
    key: 'agent_llm_ttft_ms',
    description: 'Сколько модели до первого токена ответа, миллисекунды.',
    folder: 'pipeline',
    tags: ['встроенная', 'считается', 'метрика', 'на реплику'],
    norm: '—',
    weight: 1,
    enabled: false,
    builtin: true,
  },
  {
    id: 'ch2',
    name: 'Доля речи оператора',
    key: 'talk_share_operator',
    description: 'Сколько времени всего разговора говорил оператор. Эталон — не больше 43%.',
    folder: 'default',
    tags: ['встроенная', 'считается', 'метрика'],
    norm: 'до 43%',
    weight: 2,
    enabled: true,
    builtin: true,
  },
  {
    id: 'ch3',
    name: 'Кол-во бранных слов',
    key: 'quantity_bad_words',
    description: 'Кол-во неприличных слов.',
    folder: 'mine',
    tags: ['LLM', 'метрика'],
    norm: '0–1',
    weight: 1,
    enabled: true,
    builtin: false,
  },
  {
    id: 'ch4',
    name: 'TTS: время до первого байта',
    key: 'agent_tts_ttfb_ms',
    description: 'Сколько синтез речи готовит первый байт звука, миллисекунды.',
    folder: 'pipeline',
    tags: ['встроенная', 'считается', 'метрика', 'на реплику'],
    norm: '—',
    weight: 1,
    enabled: false,
    builtin: true,
  },
  {
    id: 'ch5',
    name: 'Доля речи клиента',
    key: 'talk_share_client',
    description: 'Сколько времени всего разговора говорил клиент. Эталон — от 57%.',
    folder: 'default',
    tags: ['встроенная', 'считается', 'метрика'],
    norm: 'от 57%',
    weight: 2,
    enabled: false,
    builtin: true,
  },
  {
    id: 'ch6',
    name: 'Задержка ответа агента',
    key: 'agent_e2e_latency_ms',
    description: 'Полное время от конца реплики клиента до начала ответа агента.',
    folder: 'pipeline',
    tags: ['встроенная', 'считается'],
    norm: '—',
    weight: 1,
    enabled: false,
    builtin: true,
  },
  {
    id: 'ch7',
    name: 'Соблюдение скрипта',
    key: 'script_compliance',
    description: 'Доля обязательных блоков скрипта, которые прозвучали в разговоре.',
    folder: 'default',
    tags: ['считается', 'метрика'],
    norm: 'от 70%',
    weight: 2,
    enabled: true,
    builtin: true,
  },
  {
    id: 'ch8',
    name: 'Следующий шаг назначен',
    key: 'next_step_set',
    description: 'В разговоре зафиксированы дата, действие и ответственный.',
    folder: 'default',
    tags: ['считается', 'метрика'],
    norm: 'да',
    weight: 3,
    enabled: true,
    builtin: true,
  },
  {
    id: 'ch9',
    name: 'Возражение отработано',
    key: 'objection_handled',
    description: 'Сейл уточнил критерий сравнения и не ушёл сразу в скидку.',
    folder: 'default',
    tags: ['LLM', 'метрика'],
    norm: 'да',
    weight: 2,
    enabled: false,
    builtin: true,
  },
  {
    id: 'ch10',
    name: 'Чек-лист выполнен',
    key: 'checklist_done',
    description: 'Доля пунктов командного чек-листа, закрытых в разговоре.',
    folder: 'default',
    tags: ['считается', 'метрика'],
    norm: 'от 70%',
    weight: 2,
    enabled: true,
    builtin: true,
  },
  {
    id: 'ch11',
    name: 'Потребность выявлена',
    key: 'need_discovered',
    description: 'Сейл назвал задачу клиента своими словами и получил подтверждение.',
    folder: 'default',
    tags: ['LLM', 'метрика'],
    norm: 'да',
    weight: 2,
    enabled: true,
    builtin: true,
  },
  {
    id: 'ch12',
    name: 'Ценность донесена',
    key: 'value_delivered',
    description: 'Есть связка «задача клиента → как продукт её закрывает».',
    folder: 'default',
    tags: ['LLM', 'метрика'],
    norm: 'да',
    weight: 2,
    enabled: true,
    builtin: true,
  },
  {
    id: 'ch13',
    name: 'Длительность тишины',
    key: 'silence_ms',
    description: 'Суммарная тишина в разговоре, миллисекунды.',
    folder: 'pipeline',
    tags: ['встроенная', 'считается'],
    norm: '—',
    weight: 1,
    enabled: false,
    builtin: true,
  },
  {
    id: 'ch14',
    name: 'Перебивания оператора',
    key: 'operator_interruptions',
    description: 'Сколько раз оператор перебил клиента.',
    folder: 'default',
    tags: ['считается', 'метрика'],
    norm: 'до 2',
    weight: 1,
    enabled: true,
    builtin: true,
  },
  {
    id: 'ch15',
    name: 'Контакт установлен',
    key: 'contact_established',
    description: 'Клиент подтвердил, что удобно говорить, и представился.',
    folder: 'default',
    tags: ['считается', 'метрика'],
    norm: 'да',
    weight: 1,
    enabled: true,
    builtin: true,
  },
]

export function formatDateTime(iso: string): { date: string; time: string } {
  const d = new Date(iso)
  const date = d.toLocaleDateString('ru-RU', { day: '2-digit', month: '2-digit', year: '2-digit' })
  const time = d.toLocaleTimeString('ru-RU', { hour: '2-digit', minute: '2-digit' })
  return { date, time }
}

export function formatPct(value: number): string {
  return `${value.toFixed(1)}%`
}

export function yesNo(value: boolean | null): string {
  if (value == null) return '—'
  return value ? 'Да' : 'Нет'
}
